---
kind: pipeline
name: aws-cdk

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: ktruckenmiller/aws-cdk
      build_args:
        - CDK_VERSION=2.3.0
      username:
        from_secret: username
      password:
        from_secret: password

trigger:
  event:
    - push
    - cron
  cron: [ nightly ]
