---
kind: pipeline
name: aws-cdk
platform:
  os: linux
  arch: arm64
steps:
  - name: build
    image: plugins/docker
    settings:
      repo: ktruckenmiller/aws-cdk
      build_args:
        - CDK_VERSION=2.42.1
      username:
        from_secret: username
      password:
        from_secret: password

trigger:
  event:
    - push
  #   - cron
  # branch:
  #   - master
  # cron: [ nightly ]
