---
kind: pipeline
name: aws-cdk

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: ktruckenmiller/aws-cdk
      username:
        from_secret: username
      password:
        from_secret: password
      when:
        branch: [master]
        event: [push]
